### ISSUE TITLE
NPVoicer releaseAll

### ISSUE THREAD

**Issue by elgiano** [supercollider-quarks/JITLibExtensions#10]
Hello!

NPVoicer.releaseAll doesn't release all the nodes, nor update the playingKeys array.
I'm working on Linux with SC3.8

I suggest to change it to this:
`releaseAll { | fadeTime | proxy.removeAll(fadeTime) }`

Does it make sense?
Gianluca Elia

**Comment by adcxyz** [comment]
Hi Gianluca, 
sorry, only saw this now 
- can you post a code example that shows when/how it does not work as you expect? 

It seems to work here:
```
(
// set up an NPVoicer
g = NPVoicer(Ndef(\y), [\freq, \amp, \pan]);
g.prime(\default, false);
g.play;


fork { 
	// play random chord on it
	10.do { 
	var note = rrand(48, 96);
	g.put(note, [\freq, note.midicps]);
		0.2.wait;
	};
	1.wait;
	// release all held notes together:
	g.releaseAll(1);
};
)
```

**Comment by elgiano** [comment]
Ops, I came back here now for another issue and still found this... I still have to find my code from three years ago, and I don't use NPVoicer anymore, but I tried your reproducer and at least I can confirm that .playingKeys is not updated:
```
// ...
g.releaseAll(1);
// ...
g.playingKeys; // -> [ 48, 53, 55, 56, 61, 64, 73, 90 ]
```

**Comment by adcxyz** [comment]
thanks, you were right, fixed :-)
