### ISSUE TITLE
Help overview mixed up with CVCenter overview

### ISSUE THREAD

**Issue by nuss** [supercollider-quarks/JITLibExtensions#11]
I just realized that the overview for JITLibExtensions somehow got mixed up with the overview from a library of mine ([CVCenter](https://github.com/nuss/CVCenter), see its help overview [here](http://pustota.basislager.org/_/sc37/Help/Overviews/CVCenter.html) and compare to [JITLibExtensions' overview](http://pustota.basislager.org/_/sc37/Help/Overviews/JITLibExtensions.html)). I don't know how that happened but it's certainly confusing.

**Comment by adcxyz** [comment]
done with 294f3372
