### ISSUE TITLE
Development / bug fixes are on master branch but default is main

### ISSUE THREAD

**Issue by bgola** [supercollider-quarks/JITLibExtensions#24]
Hi,

not sure if that is correct but when I install JITLibExtensions quark it will checkout the `main` branch but recent bug fixes and development were on `master`.

Probably should merge those fixes to `main` and remove the `master` branch?

:)

**Comment by LFSaw** [comment]
@adcxyz is it possible to resolve this, please?

**Comment by adcxyz** [comment]
I merged main and master now - please test whether that solves it for you. 
I get the impression that existing older checkouts of JITLibExtensions 
may still update the checked-out master branch, while new checkouts 
hopefully take the main branch. no time to investigate ATM, sorry

**Comment by dyfer** [comment]
@adcxyz IIUC we haven't fixed SC's quarks system yet to use the default branch that's not "master". For the time being, the solution is to keep "master" up to date with "main", I'm afraid... https://github.com/supercollider/supercollider/issues/5096

**Comment by adcxyz** [comment]
@dyfer ok thanks for the clarification, and no problem to just keep them in sync 
- I was switching to "main" in order to respect the decolonializing computerese guidelines.

**Comment by dyfer** [comment]
The support for checking the default branch name in the repository was just merged into SuperCollider's develop branch. I'm not sure when the next release will happen, but once it does, it will use the default branch name as specified in the repo.

**Comment by adcxyz** [comment]
this is closed with only main branch remaining as default.

**Comment by dyfer** [comment]
Sounds good.
FYI SC 3.13 still uses master branch when checking out quarks, AFAIU. But hopefully we will release 3.14 sooner than later (no ETA).
